annotations:
  artifacthub.io/license: AGPL-3.0
apiVersion: v2
appVersion: "v0.22-dev"
description:
  Meet Plane. An open-source software development tool to manage issues,
  sprints, and product roadmaps with peace of mind.
home: https://plane.so
icon: https://plane.so/favicon/favicon-32x32.png
name: plane-helm
sources:
  - https://github.com/makeplane/plane
type: application
version: 1.2.0
dependencies:
  - name: postgresql
    version: "15.5.2"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: "19.5.1"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: minio
    version: "14.6.5"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: minio.enabled
