planeVersion: stable

dockerRegistry:
  enabled: false
  host: "index.docker.io/v1/"
  loginid: makeplane
  password: ""

ingress:
  enabled: true
  host: "plane.example.com"
  ingressClass: ""
  tls: []
  annotations: {}

redis:
  enabled: true
  auth:
    password: password
  replica:
    replicaCount: 1
  url: ""

postgresql:
  enabled: true
  url: ""
  auth:
    username: plane
    password: password
    database: plane

minio:
  enabled: true
  # this name follows the naming of the minio helm chart.
  # we only need this one name so we only ever 1 entry in this.
  defaultBuckets: "uploads"
  sizeLimit: "5242880" # 5MB
  auth:
    rootUser: admin
    rootPassword: password
  external:
    accessKey: ""
    secretKey: ""
    region: ""
    endpoint: ""

web:
  replicas: 1
  memoryLimit: 500Mi
  cpuLimit: 250m
  image: makeplane/plane-frontend

space:
  replicas: 1
  memoryLimit: 500Mi
  cpuLimit: 250m
  image: makeplane/plane-space

admin:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 250m
  image: makeplane/plane-admin

api:
  replicas: 1
  memoryLimit: 500Mi
  cpuLimit: 250m
  image: makeplane/plane-backend

worker:
  replicas: 1
  memoryLimit: 500Mi
  cpuLimit: 250m
  image: makeplane/plane-backend

beatworker:
  replicas: 1
  memoryLimit: 500Mi
  cpuLimit: 250m
  image: makeplane/plane-backend

env:
  # https://github.com/makeplane/plane/blob/preview/app.json
  secret_key: ""
  sentry_dsn: ""
  sentry_environment: ""
  gunicorn_api_workers: 1
  cors_allowed_origins: ""
  enable_signups: 1
