planeVersion: stable

dockerRegistry:
  enabled: false
  host: "index.docker.io/v1/"
  loginid: makeplane
  password: ""

ingress:
  enabled: true
  host: "plane.example.com"
  ingressClass: ""
  tls: {}
  annotations: {}

redis:
  enabled: true
  url: ""

postgresql:
  enabled: true
  url: ""
  auth:
    username: plane
    password: password
    database: plane

minio:
  local_setup: true
  image: minio/minio:latest
  storageClass: longhorn
  volumeSize: 5Gi
  root_user: admin
  root_password: password

web:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: makeplane/plane-frontend

space:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: makeplane/plane-space

admin:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: makeplane/plane-admin

api:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: makeplane/plane-backend

worker:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: makeplane/plane-backend

beatworker:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: makeplane/plane-backend

env:
  # NEXT_PUBLIC_DEPLOY_URL:  ""
  # DATA STORE
  docstore_bucket: "uploads"
  doc_upload_size_limit: "5242880" # 5MB

  # REQUIRED IF MINIO LOCAL SETUP IS FALSE
  aws_access_key: ""
  aws_secret_access_key: ""
  aws_region: ""

  secret_key: "60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5"

  sentry_dsn: ""
  sentry_environment: ""

  gunicorn_api_workers: 1

  cors_allowed_origins: ""

  enable_signups: 1
