apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-app-secrets
data:
  SECRET_KEY: {{ .Values.env.secret_key | default "60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5" | b64enc | quote }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-app-vars
data:
    SENTRY_DSN: {{ .Values.env.sentry_dsn | default "" | quote}}
    SENTRY_ENVIRONMENT: {{ .Values.env.sentry_environment | default "" | quote}}
    DEBUG: "0"
    DOCKERIZED: "1"
    GUNICORN_WORKERS: {{ .Values.env.gunicorn_api_workers | default 1 | quote }}
    ENABLE_SIGNUP: {{.Values.env.enable_signup | default 1 | quote }}

    {{- if and .Values.ingress.enabled .Values.ingress.host }}
    WEB_URL: "http://{{ .Values.ingress.host }}"
    {{- else }}
    WEB_URL: ""
    {{- end }}


    {{- if eq .Values.env.cors_allowed_origins "*"}}
    CORS_ALLOWED_ORIGINS: "*"
    {{- else if and .Values.ingress.enabled .Values.ingress.host .Values.env.cors_allowed_origins }}
    CORS_ALLOWED_ORIGINS: "http://{{ .Values.ingress.host }},https://{{ .Values.ingress.host }},{{ .Values.env.cors_allowed_origins }}"
    {{- else if .Values.env.cors_allowed_origins }}
    CORS_ALLOWED_ORIGINS: "{{ .Values.env.cors_allowed_origins }}"
    {{- else if and .Values.ingress.enabled .Values.ingress.host}}
    CORS_ALLOWED_ORIGINS: "http://{{ .Values.ingress.host }},https://{{ .Values.ingress.host }}"
    {{- else }}
    CORS_ALLOWED_ORIGINS: ""
    {{- end }}

    {{- if .Values.redis.local_setup }}
    REDIS_URL: "redis://{{ .Release.Name }}-redis.{{ .Release.Namespace }}.svc.cluster.local:6379/"
    {{- else }}
    REDIS_URL: {{ .Values.env.remote_redis_url | default "" | quote }}
    {{- end }}

    {{ if .Values.postgresql.enabled }}
    DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local/{{ .Values.postgresql.auth.database }}"
    {{ else }}
    DATABASE_URL: {{ .Values.postgresql.url }}
    {{ end }}

