
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-doc-store-secrets
stringData:
  {{ if .Values.minio.enabled }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.auth.rootPassword | quote }}
  {{ else }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.external.secretKey | quote }}
  {{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-doc-store-vars
data:
  FILE_SIZE_LIMIT: {{ .Values.minio.sizeLimit | quote }}
  AWS_S3_BUCKET_NAME: {{ .Values.minio.defaultBuckets | quote }}
  AWS_REGION: {{ .Values.minio.external.region | default "" | quote }}
  {{- if .Values.minio.enabled }}
  AWS_ACCESS_KEY_ID: {{ .Values.minio.auth.rootUser | quote }}
  {{- if and .Values.ingress.enabled .Values.ingress.host }}
  AWS_S3_ENDPOINT_URL: http{{ if .Values.ingress.tls }}s{{ end }}://{{ .Values.ingress.host }}
  {{- else }}
  AWS_S3_ENDPOINT_URL: http://{{ .Release.Name }}-minio.{{ .Release.Namespace }}:9000
  {{- end }}
  {{- else }}
  AWS_ACCESS_KEY_ID: {{ .Values.minio.external.accessKey | default "" | quote }}
  AWS_S3_ENDPOINT_URL: {{ .Values.minio.external.endpoint | default "" | quote }}
  {{- end }}
---