apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-admin
  labels:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-admin
spec:
  type: {{ .Values.admin.service.type | default "ClusterIP" }}
  ports:
  - name: admin-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-admin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-admin-wl
spec:
  replicas: {{ .Values.admin.replicas | default 1 }}
  selector:
    matchLabels:
      app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-admin
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-admin
    spec:
      containers:
      - name: {{ .Release.Name }}-admin
        {{ $i := .Values.admin.image }}
        imagePullPolicy: "{{ $i.pullPolicy }}"
        image: "{{ $i.name }}:{{ coalesce $i.tag .Values.global.image.tag .Chart.AppVersion "stable" }}"
        stdin: true
        tty: true
        resources: {{ toYaml .Values.admin.resources | nindent 10 }}
        command:
          - node
        args:
          - admin/server.js
          - admin
      serviceAccount: {{ .Release.Name }}-srv-account
      serviceAccountName: {{ .Release.Name }}-srv-account

---