
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-space
  labels:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-space
spec:
  type: {{ .Values.space.service.type | default "ClusterIP" }}
  ports:
  - name: space-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-space

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-space-wl
spec:
  replicas: {{ .Values.space.replicas | default 1 }}
  selector:
    matchLabels:
      app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-space
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-space
    spec:
      containers:
      - name: {{ .Release.Name }}-space
        {{ $i := .Values.space.image }}
        imagePullPolicy: "{{ $i.pullPolicy }}"
        image: "{{ $i.name }}:{{ coalesce $i.tag .Values.global.image.tag .Chart.AppVersion "stable" }}"
        stdin: true
        tty: true
        resources: {{ toYaml .Values.space.resources | nindent 10 }}
        command:
          - node
        args:
          - space/server.js
          - space
      serviceAccount: {{ .Release.Name }}-srv-account
      serviceAccountName: {{ .Release.Name }}-srv-account

---