apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-worker-wl
spec:
  replicas: {{ .Values.worker.replicas | default 1 }}
  selector:
    matchLabels:
      app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-worker
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-worker
    spec:
      containers:
      - name: {{ .Release.Name }}-worker
        {{ $i := .Values.worker.image }}
        imagePullPolicy: "{{ $i.pullPolicy }}"
        image: "{{ $i.name }}:{{ coalesce $i.tag .Values.global.image.tag .Chart.AppVersion "stable" }}"
        stdin: true
        tty: true
        resources: {{ toYaml .Values.worker.resources | nindent 10 }}
        command:
          - ./bin/docker-entrypoint-worker.sh
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-app-vars
              optional: false
          - secretRef:
              name: {{ .Release.Name }}-app-secrets
              optional: false
          - configMapRef:
              name: {{ .Release.Name }}-doc-store-vars
              optional: false
          - secretRef:
              name: {{ .Release.Name }}-doc-store-secrets
              optional: false

      serviceAccount: {{ .Release.Name }}-srv-account
      serviceAccountName: {{ .Release.Name }}-srv-account

---