{{- if and .Values.ingress.enabled .Values.ingress.host }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-ingress
  {{ with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClass }}
  ingressClassName: {{ .Values.ingress.ingressClass }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                port:
                  number: 3000
                name: {{ .Release.Name }}-web
            path: /
            pathType: Prefix
          - backend:
              service:
                port:
                  number: 8000
                name: {{ .Release.Name }}-api
            path: /api
            pathType: Prefix
          - backend:
              service:
                port:
                  number: 8000
                name: {{ .Release.Name }}-api
            path: /auth
            pathType: Prefix
          - backend:
              service:
                port:
                  number: 3000
                name: {{ .Release.Name }}-space
            path: /spaces
            pathType: Prefix
          - backend:
              service:
                port:
                  number: 3000
                name: {{ .Release.Name }}-admin
            path: /god-mode
            pathType: Prefix
          {{- if .Values.minio.enabled }}
          - backend:
              service:
                port:
                  number: 9000
                name: {{ .Release.Name }}-minio
            path: /{{ .Values.minio.defaultBuckets }}
            pathType: Prefix
          {{- end }}
  {{- with .Values.ingress.tls }}
  tls: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}