name: Release Charts

on:
  push:
    tags:
      - 1.**

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run chart-releaser
        uses: Karitham/helm-oci-chart-releaser@b720e7e58d9e73b06f71f027ab61b54cb46b0964
        with:
          name: plane-helm
          tag: ${{ github.ref_name }}
          path: ./
          registry: ghcr.io/karitham
          repository: plane-helm
          registry_username: karitham
          registry_password: ${{ secrets.GITHUB_TOKEN }}
