name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Chart version
        id: chart_version
        run: echo "chart_version=$(cat ./Chart.yaml | grep '^version:' | awk '{print $2}')" >> "$GITHUB_OUTPUT"

      - name: Run chart-releaser
        uses: Karitham/helm-oci-chart-releaser@b720e7e58d9e73b06f71f027ab61b54cb46b0964
        with:
          name: plane-helm
          tag: ${{ steps.chart_version.outputs.chart_version }}
          path: ./
          registry: ghcr.io/karitham
          repository: plane-helm
          registry_username: karitham
          registry_password: ${{ secrets.GITHUB_TOKEN }}
